(module (algebraic-structures functor vector base) (map)
  (import (rename scheme (map list-map))
          (only (chicken base) add1))

  (define (map f v)
    (let* ((len (vector-length v))
           (new (make-vector len)))
      (do ((i 0 (add1 i)))
          ((= i len) new)
        (vector-set! new i (vector-ref v i))))))
